name: VariaBukkit
version: '1.0-SNAPSHOT'
main: xyz.article.variaBukkit.VariaBukkit
api-version: '1.20'
authors: ["NekoEpisode", "Xiaotian1212"]

commands:
  VariaBukkit:
    description: VariaBukkit主命令
    permission: VariaBukkit.VariaBukkit
    aliases: ["vb"]
  report:
    description: 举报命令
    permission: VariaBukkit.Report


permissions:
  VariaBukkit.VariaBukkit:
    default: true
  VariaBukkit.Reload:
    default: op
  VariaBukkit.Report:
    default: true