name: VariaBukkit
version: '1.0-SNAPSHOT'
main: xyz.article.variaBukkit.VariaBukkit
api-version: '1.20'
authors: ["NekoEpisode"]

commands:
  VariaBukkit:
    description: VariaBukkit主命令
    permission: VariaBukkit.VariaBukkit
    aliases: ["vb"]
  report:
    description: Allows players to report other players.
    usage: /report <playerName> <reason>


permissions:
  VariaBukkit.VariaBukkit:
    default: true
  VariaBukkit.Reload:
    default: op