name: VariaBukkit
version: '1.0-SNAPSHOT'
main: xyz.article.varia.bukkit.VariaBukkit
api-version: '1.20'
authors: ["NekoEpisode", "Xiaotian1212"]

permissions:
  Varia.VariaBukkit:
    default: true
  Varia.Reload:
    default: op
  Varia.Report:
    default: true