#欢迎来到VariaBukkit配置文件
#如果您当前进入的是default_config.yml，那么请转到config.yml，因为您在这里的修改不会被读取且会被覆盖
#default_config.yml是为了防止配置文件自动更新后丢失注释的，如果您在更新后找不到注释，可以尝试查看default_config.yml来对照

#屏蔽词系统
#是否开启屏蔽词系统?
BlockWord: false
#屏蔽词列表
BlockWords:
  - "example"
  - "example2"
#屏蔽词模式
#在检测到屏蔽词后应替换为自定义的替换字符还是直接取消消息发送
#可填项Replace, Cancel
BlockWordMode: "Replace"
#Replace模式要替换的字符
ReplaceWord: "*"

#举报系统
#是否在收到新举报时显示标题提示?
ReportTitle: true
#预设举报理由
ReportReasons:
  - "作弊"
  - "侮辱"
  - "破坏"