#欢迎来到VariaBukkit配置文件

#屏蔽词系统
#是否开启屏蔽词系统?
BlockWord: false
#屏蔽词列表
BlockWords:
  - "example"
  - "example2"
#屏蔽词模式
#在检测到屏蔽词后应替换为自定义的替换字符还是直接取消消息发送
#可填项Replace, Cancel
BlockWordMode: "Replace"
#Replace模式要替换的字符
ReplaceWord: "*"

#举报系统
#是否在收到新举报时显示标题提示?
ReportTitle: true
#预设举报理由
ReportReasons:
  - "作弊"
  - "侮辱"
  - "破坏"